//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.28 at 07:20:13 PM CEST 
//


package it.polito.dp2.FDS.sol4.service.xsdpack;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FlightMonitorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FlightMonitorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Aircrafts" type="{http://www.example.org/FDSInfo_schema/}AircraftsType"/>
 *         &lt;element name="Flights" type="{http://www.example.org/FDSInfo_schema/}FlightsType"/>
 *         &lt;element name="FlightInstances" type="{http://www.example.org/FDSInfo_schema/}FlightInstancesType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlightMonitorType", propOrder = {
    "aircrafts",
    "flights",
    "flightInstances"
})
public class FlightMonitorType {

    @XmlElement(name = "Aircrafts", required = true)
    protected AircraftsType aircrafts;
    @XmlElement(name = "Flights", required = true)
    protected FlightsType flights;
    @XmlElement(name = "FlightInstances", required = true)
    protected FlightInstancesType flightInstances;

    /**
     * Gets the value of the aircrafts property.
     * 
     * @return
     *     possible object is
     *     {@link AircraftsType }
     *     
     */
    public AircraftsType getAircrafts() {
        return aircrafts;
    }

    /**
     * Sets the value of the aircrafts property.
     * 
     * @param value
     *     allowed object is
     *     {@link AircraftsType }
     *     
     */
    public void setAircrafts(AircraftsType value) {
        this.aircrafts = value;
    }

    /**
     * Gets the value of the flights property.
     * 
     * @return
     *     possible object is
     *     {@link FlightsType }
     *     
     */
    public FlightsType getFlights() {
        return flights;
    }

    /**
     * Sets the value of the flights property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightsType }
     *     
     */
    public void setFlights(FlightsType value) {
        this.flights = value;
    }

    /**
     * Gets the value of the flightInstances property.
     * 
     * @return
     *     possible object is
     *     {@link FlightInstancesType }
     *     
     */
    public FlightInstancesType getFlightInstances() {
        return flightInstances;
    }

    /**
     * Sets the value of the flightInstances property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightInstancesType }
     *     
     */
    public void setFlightInstances(FlightInstancesType value) {
        this.flightInstances = value;
    }

}
