
package org.example.fdscontrol;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CheckInOperationService", targetNamespace = "http://www.example.org/FDSControl/", wsdlLocation = "file:/Users/ivano/Dropbox/Politecnico/3%20Anno%20LM/DP%20II/Pratica/Assignment4b/wsdl/FDSControl.wsdl")
public class CheckInOperationService
    extends Service
{

    private final static URL CHECKINOPERATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException CHECKINOPERATIONSERVICE_EXCEPTION;
    private final static QName CHECKINOPERATIONSERVICE_QNAME = new QName("http://www.example.org/FDSControl/", "CheckInOperationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/ivano/Dropbox/Politecnico/3%20Anno%20LM/DP%20II/Pratica/Assignment4b/wsdl/FDSControl.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CHECKINOPERATIONSERVICE_WSDL_LOCATION = url;
        CHECKINOPERATIONSERVICE_EXCEPTION = e;
    }

    public CheckInOperationService() {
        super(__getWsdlLocation(), CHECKINOPERATIONSERVICE_QNAME);
    }

    public CheckInOperationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CHECKINOPERATIONSERVICE_QNAME, features);
    }

    public CheckInOperationService(URL wsdlLocation) {
        super(wsdlLocation, CHECKINOPERATIONSERVICE_QNAME);
    }

    public CheckInOperationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CHECKINOPERATIONSERVICE_QNAME, features);
    }

    public CheckInOperationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CheckInOperationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CheckinOperationPort
     */
    @WebEndpoint(name = "CheckinOperationSOAP")
    public CheckinOperationPort getCheckinOperationSOAP() {
        return super.getPort(new QName("http://www.example.org/FDSControl/", "CheckinOperationSOAP"), CheckinOperationPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CheckinOperationPort
     */
    @WebEndpoint(name = "CheckinOperationSOAP")
    public CheckinOperationPort getCheckinOperationSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/FDSControl/", "CheckinOperationSOAP"), CheckinOperationPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CHECKINOPERATIONSERVICE_EXCEPTION!= null) {
            throw CHECKINOPERATIONSERVICE_EXCEPTION;
        }
        return CHECKINOPERATIONSERVICE_WSDL_LOCATION;
    }

}
