
package org.example.fdscontrol;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FDSControlService", targetNamespace = "http://www.example.org/FDSControl/", wsdlLocation = "file:/Users/ivano/Dropbox/Politecnico/3%20Anno%20LM/DP%20II/Pratica/Assignment4b/wsdl/FDSControl.wsdl")
public class FDSControlService
    extends Service
{

    private final static URL FDSCONTROLSERVICE_WSDL_LOCATION;
    private final static WebServiceException FDSCONTROLSERVICE_EXCEPTION;
    private final static QName FDSCONTROLSERVICE_QNAME = new QName("http://www.example.org/FDSControl/", "FDSControlService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/ivano/Dropbox/Politecnico/3%20Anno%20LM/DP%20II/Pratica/Assignment4b/wsdl/FDSControl.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FDSCONTROLSERVICE_WSDL_LOCATION = url;
        FDSCONTROLSERVICE_EXCEPTION = e;
    }

    public FDSControlService() {
        super(__getWsdlLocation(), FDSCONTROLSERVICE_QNAME);
    }

    public FDSControlService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FDSCONTROLSERVICE_QNAME, features);
    }

    public FDSControlService(URL wsdlLocation) {
        super(wsdlLocation, FDSCONTROLSERVICE_QNAME);
    }

    public FDSControlService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FDSCONTROLSERVICE_QNAME, features);
    }

    public FDSControlService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FDSControlService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FDSControl
     */
    @WebEndpoint(name = "FDSControlSOAP")
    public FDSControl getFDSControlSOAP() {
        return super.getPort(new QName("http://www.example.org/FDSControl/", "FDSControlSOAP"), FDSControl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FDSControl
     */
    @WebEndpoint(name = "FDSControlSOAP")
    public FDSControl getFDSControlSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/FDSControl/", "FDSControlSOAP"), FDSControl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FDSCONTROLSERVICE_EXCEPTION!= null) {
            throw FDSCONTROLSERVICE_EXCEPTION;
        }
        return FDSCONTROLSERVICE_WSDL_LOCATION;
    }

}
