
package org.example.fdscontrol;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InstanceNotFoundError", targetNamespace = "http://www.example.org/FDSControl/")
public class InstanceNotFoundMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InstanceNotFoundError faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InstanceNotFoundMessage(String message, InstanceNotFoundError faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public InstanceNotFoundMessage(String message, InstanceNotFoundError faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.example.fdscontrol.InstanceNotFoundError
     */
    public InstanceNotFoundError getFaultInfo() {
        return faultInfo;
    }

}
