
package it.polito.dp2.FDS.sol4.service.Control;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OtherOperationService", targetNamespace = "http://www.example.org/FDSControl/", wsdlLocation = "file:/Users/ivano/Desktop/Assignment4b/wsdl/FDSControl.wsdl")
public class OtherOperationService
    extends Service
{

    private final static URL OTHEROPERATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException OTHEROPERATIONSERVICE_EXCEPTION;
    private final static QName OTHEROPERATIONSERVICE_QNAME = new QName("http://www.example.org/FDSControl/", "OtherOperationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/ivano/Desktop/Assignment4b/wsdl/FDSControl.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OTHEROPERATIONSERVICE_WSDL_LOCATION = url;
        OTHEROPERATIONSERVICE_EXCEPTION = e;
    }

    public OtherOperationService() {
        super(__getWsdlLocation(), OTHEROPERATIONSERVICE_QNAME);
    }

    public OtherOperationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), OTHEROPERATIONSERVICE_QNAME, features);
    }

    public OtherOperationService(URL wsdlLocation) {
        super(wsdlLocation, OTHEROPERATIONSERVICE_QNAME);
    }

    public OtherOperationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OTHEROPERATIONSERVICE_QNAME, features);
    }

    public OtherOperationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OtherOperationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OtherOperationPort
     */
    @WebEndpoint(name = "OtherOperationSOAP")
    public OtherOperationPort getOtherOperationSOAP() {
        return super.getPort(new QName("http://www.example.org/FDSControl/", "OtherOperationSOAP"), OtherOperationPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OtherOperationPort
     */
    @WebEndpoint(name = "OtherOperationSOAP")
    public OtherOperationPort getOtherOperationSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/FDSControl/", "OtherOperationSOAP"), OtherOperationPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OTHEROPERATIONSERVICE_EXCEPTION!= null) {
            throw OTHEROPERATIONSERVICE_EXCEPTION;
        }
        return OTHEROPERATIONSERVICE_WSDL_LOCATION;
    }

}
