
package org.example.fdsinfo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FDSInfoService", targetNamespace = "http://www.example.org/FDSInfo/", wsdlLocation = "file:/Users/ivano/Dropbox/Politecnico/3%20Anno%20LM/DP%20II/Pratica/Assignment4b/wsdl/FDSInfo.wsdl")
public class FDSInfoService
    extends Service
{

    private final static URL FDSINFOSERVICE_WSDL_LOCATION;
    private final static WebServiceException FDSINFOSERVICE_EXCEPTION;
    private final static QName FDSINFOSERVICE_QNAME = new QName("http://www.example.org/FDSInfo/", "FDSInfoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/ivano/Dropbox/Politecnico/3%20Anno%20LM/DP%20II/Pratica/Assignment4b/wsdl/FDSInfo.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FDSINFOSERVICE_WSDL_LOCATION = url;
        FDSINFOSERVICE_EXCEPTION = e;
    }

    public FDSInfoService() {
        super(__getWsdlLocation(), FDSINFOSERVICE_QNAME);
    }

    public FDSInfoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FDSINFOSERVICE_QNAME, features);
    }

    public FDSInfoService(URL wsdlLocation) {
        super(wsdlLocation, FDSINFOSERVICE_QNAME);
    }

    public FDSInfoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FDSINFOSERVICE_QNAME, features);
    }

    public FDSInfoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FDSInfoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FDSInfo
     */
    @WebEndpoint(name = "FDSInfoSOAP")
    public FDSInfo getFDSInfoSOAP() {
        return super.getPort(new QName("http://www.example.org/FDSInfo/", "FDSInfoSOAP"), FDSInfo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FDSInfo
     */
    @WebEndpoint(name = "FDSInfoSOAP")
    public FDSInfo getFDSInfoSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/FDSInfo/", "FDSInfoSOAP"), FDSInfo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FDSINFOSERVICE_EXCEPTION!= null) {
            throw FDSINFOSERVICE_EXCEPTION;
        }
        return FDSINFOSERVICE_WSDL_LOCATION;
    }

}
