
package it.polito.dp2.FDS.sol4.service.Info;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import it.polito.dp2.FDS.sol4.service.xsdpack.AircraftType;
import it.polito.dp2.FDS.sol4.service.xsdpack.FlightInstanceReaderType;
import it.polito.dp2.FDS.sol4.service.xsdpack.FlightMonitorType;
import it.polito.dp2.FDS.sol4.service.xsdpack.FlightReaderType;
import it.polito.dp2.FDS.sol4.service.xsdpack.PassengerReaderType;
import it.polito.dp2.FDS.sol4.service.xsdpack.StatusType;
import it.polito.dp2.FDS.sol4.service.xsdpack.TimeType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FDSInfo", targetNamespace = "http://www.example.org/FDSInfo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FDSInfo {


    /**
     * 
     * @param model
     * @return
     *     returns java.util.List<it.polito.dp2.FDS.sol4.service.xsdpack.AircraftType>
     * @throws GetAircraftsFault
     */
    @WebMethod(action = "http://www.example.org/FDSInfo/getAircrafts")
    @WebResult(name = "Aircrafts", targetNamespace = "")
    @RequestWrapper(localName = "getAircrafts", targetNamespace = "http://www.example.org/FDSInfo/", className = "it.polito.dp2.FDS.sol4.service.Info.GetAircraftsRequestType")
    @ResponseWrapper(localName = "getAircraftsResponse", targetNamespace = "http://www.example.org/FDSInfo/", className = "it.polito.dp2.FDS.sol4.service.Info.GetAircraftsResponseType")
    public List<AircraftType> getAircrafts(
        @WebParam(name = "model", targetNamespace = "")
        String model)
        throws GetAircraftsFault
    ;

    /**
     * 
     * @param time
     * @param departure
     * @param destination
     * @return
     *     returns java.util.List<it.polito.dp2.FDS.sol4.service.xsdpack.FlightReaderType>
     * @throws GetFlightsParamErr
     * @throws GetFlightsFault
     */
    @WebMethod(action = "http://www.example.org/FDSInfo/getFlights")
    @WebResult(name = "Flights", targetNamespace = "")
    @RequestWrapper(localName = "getFlights", targetNamespace = "http://www.example.org/FDSInfo/", className = "it.polito.dp2.FDS.sol4.service.Info.GetFlightsRequestType")
    @ResponseWrapper(localName = "getFlightsResponse", targetNamespace = "http://www.example.org/FDSInfo/", className = "it.polito.dp2.FDS.sol4.service.Info.GetFlightsResponseType")
    public List<FlightReaderType> getFlights(
        @WebParam(name = "Departure", targetNamespace = "")
        String departure,
        @WebParam(name = "Destination", targetNamespace = "")
        String destination,
        @WebParam(name = "Time", targetNamespace = "")
        TimeType time)
        throws GetFlightsFault, GetFlightsParamErr
    ;

    /**
     * 
     * @param status
     * @param flightNumber
     * @param date
     * @return
     *     returns java.util.List<it.polito.dp2.FDS.sol4.service.xsdpack.FlightInstanceReaderType>
     * @throws GetInstancesFault
     */
    @WebMethod(action = "http://www.example.org/FDSInfo/getInstances")
    @WebResult(name = "FlightInstances", targetNamespace = "")
    @RequestWrapper(localName = "getInstances", targetNamespace = "http://www.example.org/FDSInfo/", className = "it.polito.dp2.FDS.sol4.service.Info.GetInstancesRequestType")
    @ResponseWrapper(localName = "getInstancesResponse", targetNamespace = "http://www.example.org/FDSInfo/", className = "it.polito.dp2.FDS.sol4.service.Info.GetInstancesResponseType")
    public List<FlightInstanceReaderType> getInstances(
        @WebParam(name = "flightNumber", targetNamespace = "")
        String flightNumber,
        @WebParam(name = "date", targetNamespace = "")
        XMLGregorianCalendar date,
        @WebParam(name = "status", targetNamespace = "")
        StatusType status)
        throws GetInstancesFault
    ;

    /**
     * 
     * @param flightNumber
     * @param date
     * @return
     *     returns java.util.List<it.polito.dp2.FDS.sol4.service.xsdpack.PassengerReaderType>
     * @throws GetPassengersFault
     */
    @WebMethod(action = "http://www.example.org/FDSInfo/getPassengers")
    @WebResult(name = "Passengers", targetNamespace = "")
    @RequestWrapper(localName = "getPassengers", targetNamespace = "http://www.example.org/FDSInfo/", className = "it.polito.dp2.FDS.sol4.service.Info.GetPassengersType")
    @ResponseWrapper(localName = "getPassengersResponse", targetNamespace = "http://www.example.org/FDSInfo/", className = "it.polito.dp2.FDS.sol4.service.Info.GetPassengersResponseType")
    public List<PassengerReaderType> getPassengers(
        @WebParam(name = "date", targetNamespace = "")
        XMLGregorianCalendar date,
        @WebParam(name = "flightNumber", targetNamespace = "")
        String flightNumber)
        throws GetPassengersFault
    ;

    /**
     * 
     * @param name
     * @param flightNumber
     * @param date
     * @return
     *     returns it.polito.dp2.FDS.sol4.service.xsdpack.PassengerReaderType
     * @throws GetPassengerFault
     */
    @WebMethod(action = "http://www.example.org/FDSInfo/getPassenger")
    @WebResult(name = "Passenger", targetNamespace = "")
    @RequestWrapper(localName = "getPassenger", targetNamespace = "http://www.example.org/FDSInfo/", className = "it.polito.dp2.FDS.sol4.service.Info.GetPassengerRequestType")
    @ResponseWrapper(localName = "getPassengerResponse", targetNamespace = "http://www.example.org/FDSInfo/", className = "it.polito.dp2.FDS.sol4.service.Info.GetPassengerResponseType")
    public PassengerReaderType getPassenger(
        @WebParam(name = "date", targetNamespace = "")
        XMLGregorianCalendar date,
        @WebParam(name = "flightNumber", targetNamespace = "")
        String flightNumber,
        @WebParam(name = "name", targetNamespace = "")
        String name)
        throws GetPassengerFault
    ;

    /**
     * 
     * @param flightNumber
     * @return
     *     returns it.polito.dp2.FDS.sol4.service.xsdpack.FlightReaderType
     * @throws GetFlightFault
     */
    @WebMethod(action = "http://www.example.org/FDSInfo/getFlight")
    @WebResult(name = "Flight", targetNamespace = "")
    @RequestWrapper(localName = "getFlight", targetNamespace = "http://www.example.org/FDSInfo/", className = "it.polito.dp2.FDS.sol4.service.Info.GetFlightRequestType")
    @ResponseWrapper(localName = "getFlightResponse", targetNamespace = "http://www.example.org/FDSInfo/", className = "it.polito.dp2.FDS.sol4.service.Info.GetFlightResponseType")
    public FlightReaderType getFlight(
        @WebParam(name = "flightNumber", targetNamespace = "")
        String flightNumber)
        throws GetFlightFault
    ;

    /**
     * 
     * @param flightNumber
     * @param date
     * @return
     *     returns it.polito.dp2.FDS.sol4.service.xsdpack.FlightInstanceReaderType
     * @throws GetInstanceFault
     */
    @WebMethod(action = "http://www.example.org/FDSInfo/getI")
    @WebResult(name = "FlightInstance", targetNamespace = "")
    @RequestWrapper(localName = "getInstance", targetNamespace = "http://www.example.org/FDSInfo/", className = "it.polito.dp2.FDS.sol4.service.Info.GetInstanceRequestType")
    @ResponseWrapper(localName = "getInstanceResponse", targetNamespace = "http://www.example.org/FDSInfo/", className = "it.polito.dp2.FDS.sol4.service.Info.GetInstanceResponseType")
    public FlightInstanceReaderType getInstance(
        @WebParam(name = "flightNumber", targetNamespace = "")
        String flightNumber,
        @WebParam(name = "date", targetNamespace = "")
        XMLGregorianCalendar date)
        throws GetInstanceFault
    ;

    /**
     * 
     * @return
     *     returns it.polito.dp2.FDS.sol4.service.xsdpack.FlightMonitorType
     * @throws GetAllFault
     */
    @WebMethod(action = "http://www.example.org/FDSInfo/getAll")
    @WebResult(name = "FlightMonitor", targetNamespace = "")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://www.example.org/FDSInfo/", className = "it.polito.dp2.FDS.sol4.service.Info.GetAllRequestType")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://www.example.org/FDSInfo/", className = "it.polito.dp2.FDS.sol4.service.Info.GetAllResponseType")
    public FlightMonitorType getAll()
        throws GetAllFault
    ;

}
