
package it.polito.dp2.FDS.sol4.service.Info;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "getFlightFault", targetNamespace = "http://www.example.org/FDSInfo/")
public class GetFlightFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private GetFlightFaultType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public GetFlightFault(String message, GetFlightFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public GetFlightFault(String message, GetFlightFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: it.polito.dp2.FDS.sol4.service.Info.GetFlightFaultType
     */
    public GetFlightFaultType getFaultInfo() {
        return faultInfo;
    }

}
